### ISSUE TITLE
Behaviour of single quotes with `luaquotes` packages is not consistent

### ISSUE THREAD

**Issue by kleinbottle** [ezgranet/luaquotes#3]
Please see:

https://tex.stackexchange.com/questions/666172/behaviour-of-single-quotes-with-luaquotes-packages-is-not-consistent

**Comment by ezgranet** [comment]
Thanks for bringing this to my attention: I will look at this and give an  answer on SE shortly!

**Comment by ezgranet** [comment]
Fixed with latest  commit!
