### ISSUE TITLE
Wish: Add option for Swiss German quotation

### ISSUE THREAD

**Issue by lemzwerg** [ezgranet/luaquotes#6]
In Swiss German, the quotation style with guillemets is exactly the opposite of the one used in Austria and Germany:

> «Das ist ein ‹interessantes› Ergebnis.»

As can be seen, it differs from the French version by not inserting extra spaces.

Please add this!

**Comment by ezgranet** [comment]
Great idea! I will add that this week

**Comment by ezgranet** [comment]
Support added in latest commit! The CTAN maintainers should push it out via TeX Live by tomorrow at latest, but in the meantime you can always download from the repo. 

As noted in updated documentation, you just use 

`\usepackage[dech]{luaquotes}`
